### ISSUE TITLE
Parameterized deployment support

### ISSUE THREAD

**Issue by colinjfw** [deliverybot/deploybot#27]
Allow deploying with variables that can be interpolated into the payload of the deployment. Similar to parameterized builds in Jenkins.

**Comment by jbergstroem** [comment]
Reading from a file in repo would be awfully convenient as well (that can be overwritten via the parameterized deploy)!

**Comment by missedone** [comment]
github slackbot support pass in the deployment payload: https://github.com/integrations/slack

however i'm looking for the same feature as well in deliverybot since i want to trigger the deployment either with slack or the web gui

thanks

**Comment by missedone** [comment]
ok, we can implement parameterize build with payload: https://deliverybot.dev/docs/configuration/#targetpayload

but noticed that the payload format is different with github slack.
deliverybot defines the payload as object (aka, JSON/Yaml object), while github slack is just raw string, it's inconsistent.
i'd suggest to support raw json string to be consistent with slack, Example:

prefer
```yaml
production:
  environment: production
  production_environment: true
  payload: |
    {"foor": "bar"}
```
over
```yaml
production:
  environment: production
  production_environment: true
  payload: 
    foo: bar
```
