### ISSUE TITLE
Monorepo deployments

### ISSUE THREAD

**Issue by colinjfw** [deliverybot/deploybot#28]
Select from a dropdown of services to deploy. Will show commits only from that path.

```yaml
# .github/deploy.yml
services:
- name: foo
  path: bar
```
